/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ui;

import javax.swing.ImageIcon;


/**
 *
 * @author nicle
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/com/mycompany/images/miBilletera.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBG = new javax.swing.JPanel();
        jPanelMeses = new javax.swing.JPanel();
        jComboBoxAnios = new javax.swing.JComboBox<>();
        jLabelEnero = new javax.swing.JLabel();
        jLabelFebrero = new javax.swing.JLabel();
        jLabelMarzo = new javax.swing.JLabel();
        jLabelAbril = new javax.swing.JLabel();
        jLabelMayo = new javax.swing.JLabel();
        jLabelJunio = new javax.swing.JLabel();
        jLabelJulio = new javax.swing.JLabel();
        jLabelAgosto = new javax.swing.JLabel();
        jLabelSeptiembre = new javax.swing.JLabel();
        jLabelOctubre = new javax.swing.JLabel();
        jLabelNoviembre = new javax.swing.JLabel();
        jLabelDiciembre = new javax.swing.JLabel();
        jPanelBalance = new javax.swing.JPanel();
        jPanelTitulosCuentas = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabelBalance = new javax.swing.JLabel();
        jLabelSignoPesosBalance = new javax.swing.JLabel();
        jLabelSignoDolarBalance = new javax.swing.JLabel();
        jLabelCantPesosBalance = new javax.swing.JLabel();
        jLabelCantDolaresBalance = new javax.swing.JLabel();
        jLabelTotalPesosDolares = new javax.swing.JLabel();
        jScrollPaneCuentas = new javax.swing.JScrollPane();
        jTableCuentas = new javax.swing.JTable();
        jLabelIngresos = new javax.swing.JLabel();
        jLabelGastos = new javax.swing.JLabel();
        jLabelCantIngresos = new javax.swing.JLabel();
        jLabelCantGstos = new javax.swing.JLabel();
        jLabelViewImagenBalance = new javax.swing.JLabel();
        jLabelPrintImagen = new javax.swing.JLabel();
        jLabelChartImagenBalance = new javax.swing.JLabel();
        jLabelVerDineroBalance = new javax.swing.JLabel();
        jLabelGraficosBalance = new javax.swing.JLabel();
        jLabelImprimir = new javax.swing.JLabel();
        jPanelTransacciones = new javax.swing.JPanel();
        jPanelTitulosTransacciones = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabelTransacciones = new javax.swing.JLabel();
        jScrollPaneTransacciones = new javax.swing.JScrollPane();
        jTableTransacciones = new javax.swing.JTable();
        jLabelSearchImagenTrans = new javax.swing.JLabel();
        jLabelSortImagen = new javax.swing.JLabel();
        jLabelBuscarTransaccion = new javax.swing.JLabel();
        jLabelOrdenarPor = new javax.swing.JLabel();
        jPanelSube = new javax.swing.JPanel();
        jLabelMontoSube = new javax.swing.JLabel();
        jLabelSignoPesoSube = new javax.swing.JLabel();
        jLabelNumeroSube = new javax.swing.JLabel();
        jLabelSubeImagen = new javax.swing.JLabel();
        jLabelSube = new javax.swing.JLabel();
        jLabelSearchImagenSube = new javax.swing.JLabel();
        jLabelViewImagenSube = new javax.swing.JLabel();
        jLabelBuscarSube = new javax.swing.JLabel();
        jLabelVerDineroSube = new javax.swing.JLabel();
        jPanelAhorros = new javax.swing.JPanel();
        jPanelTitulosAhorros = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabelAhorros = new javax.swing.JLabel();
        jScrollPaneAhorros = new javax.swing.JScrollPane();
        jTableAhorros = new javax.swing.JTable();
        jLabelCantDolaresAhorros = new javax.swing.JLabel();
        jLabelSignoDolarAhorros = new javax.swing.JLabel();
        jLabelSignoPesosAhorros = new javax.swing.JLabel();
        jLabelCantPesosAhorros = new javax.swing.JLabel();
        jLabelTotalPesosEqDolares = new javax.swing.JLabel();
        jLabelChartImagenAhorros = new javax.swing.JLabel();
        jLabelViewImagenAhorros = new javax.swing.JLabel();
        jLabelGraficosAhorros = new javax.swing.JLabel();
        jLabelVerDineroAhorros = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabelTransactionsImagen = new javax.swing.JLabel();
        jLabelSubeFuncionImagen = new javax.swing.JLabel();
        jLabelBankImagen = new javax.swing.JLabel();
        jLabelCategoriesImagen = new javax.swing.JLabel();
        jLabelSavingsImagen = new javax.swing.JLabel();
        jLabelTransaccionesFuncion = new javax.swing.JLabel();
        jLabelSubeFuncion = new javax.swing.JLabel();
        jLabelCategoriasFuncion = new javax.swing.JLabel();
        jLabelCuentasFuncion = new javax.swing.JLabel();
        jLabelAhorrosFuncion = new javax.swing.JLabel();
        jLabelFondoLogo = new javax.swing.JLabel();
        jLabelFondoLogo1 = new javax.swing.JLabel();
        jLabelFondoLogo2 = new javax.swing.JLabel();
        jLabelFondoLogo3 = new javax.swing.JLabel();
        jLabelFondoLogo4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi Billetera");
        setBackground(new java.awt.Color(229, 238, 230));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1366, 720));

        jPanelBG.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBG.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBG.setPreferredSize(new java.awt.Dimension(1366, 720));
        jPanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMeses.setBackground(new java.awt.Color(52, 84, 61));
        jPanelMeses.setPreferredSize(new java.awt.Dimension(220, 720));

        jComboBoxAnios.setBackground(new java.awt.Color(166, 197, 175));
        jComboBoxAnios.setEditable(true);
        jComboBoxAnios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxAnios.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxAnios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar año" }));
        jComboBoxAnios.setToolTipText("Seleccionar año");
        jComboBoxAnios.setBorder(null);
        jComboBoxAnios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxAnios.setName(""); // NOI18N

        jLabelEnero.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEnero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEnero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEnero.setText("ENERO");
        jLabelEnero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelFebrero.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFebrero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFebrero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFebrero.setText("FEBRERO");
        jLabelFebrero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelMarzo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMarzo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMarzo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMarzo.setText("MARZO");
        jLabelMarzo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelAbril.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAbril.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAbril.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAbril.setText("ABRIL");
        jLabelAbril.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelMayo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMayo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMayo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMayo.setText("MAYO");
        jLabelMayo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelJunio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelJunio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelJunio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJunio.setText("JUNIO");
        jLabelJunio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelJulio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelJulio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelJulio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJulio.setText("JULIO");
        jLabelJulio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelAgosto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAgosto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAgosto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgosto.setText("AGOSTO");
        jLabelAgosto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelSeptiembre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSeptiembre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSeptiembre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeptiembre.setText("SEPTIEMBRE");
        jLabelSeptiembre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelOctubre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOctubre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelOctubre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOctubre.setText("OCTUBRE");
        jLabelOctubre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelNoviembre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNoviembre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNoviembre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNoviembre.setText("NOVIEMBRE");
        jLabelNoviembre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelDiciembre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDiciembre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDiciembre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiciembre.setText("DICIEMBRE");
        jLabelDiciembre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelMesesLayout = new javax.swing.GroupLayout(jPanelMeses);
        jPanelMeses.setLayout(jPanelMesesLayout);
        jPanelMesesLayout.setHorizontalGroup(
            jPanelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBoxAnios, 0, 220, Short.MAX_VALUE)
            .addGroup(jPanelMesesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDiciembre)
                    .addComponent(jLabelNoviembre)
                    .addComponent(jLabelOctubre)
                    .addComponent(jLabelSeptiembre)
                    .addComponent(jLabelAgosto)
                    .addComponent(jLabelJulio)
                    .addComponent(jLabelJunio)
                    .addComponent(jLabelMayo)
                    .addComponent(jLabelAbril)
                    .addComponent(jLabelMarzo)
                    .addComponent(jLabelFebrero)
                    .addComponent(jLabelEnero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMesesLayout.setVerticalGroup(
            jPanelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMesesLayout.createSequentialGroup()
                .addComponent(jComboBoxAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEnero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFebrero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMarzo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAbril)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMayo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelJunio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelJulio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAgosto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSeptiembre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOctubre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNoviembre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDiciembre)
                .addGap(0, 270, Short.MAX_VALUE))
        );

        jPanelBG.add(jPanelMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 690));

        jPanelBalance.setBackground(new java.awt.Color(240, 247, 241));
        jPanelBalance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitulosCuentas.setBackground(new java.awt.Color(52, 84, 61));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("PESOS");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("CUENTA");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("DOLARES");

        javax.swing.GroupLayout jPanelTitulosCuentasLayout = new javax.swing.GroupLayout(jPanelTitulosCuentas);
        jPanelTitulosCuentas.setLayout(jPanelTitulosCuentasLayout);
        jPanelTitulosCuentasLayout.setHorizontalGroup(
            jPanelTitulosCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitulosCuentasLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTitulosCuentasLayout.setVerticalGroup(
            jPanelTitulosCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitulosCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBalance.add(jPanelTitulosCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 510, 30));

        jLabelBalance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBalance.setText("BALANCE");
        jPanelBalance.add(jLabelBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 15, -1, -1));

        jLabelSignoPesosBalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelSignoPesosBalance.setText("$");
        jPanelBalance.add(jLabelSignoPesosBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 42, -1, -1));

        jLabelSignoDolarBalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelSignoDolarBalance.setText("USD");
        jPanelBalance.add(jLabelSignoDolarBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 80, -1, -1));

        jLabelCantPesosBalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCantPesosBalance.setText("0");
        jPanelBalance.add(jLabelCantPesosBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 42, 335, -1));

        jLabelCantDolaresBalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCantDolaresBalance.setText("0");
        jPanelBalance.add(jLabelCantDolaresBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 80, 335, -1));

        jLabelTotalPesosDolares.setText("Total de Pesos y total de Dolares");
        jPanelBalance.add(jLabelTotalPesosDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 118, -1, -1));

        jScrollPaneCuentas.setBackground(new java.awt.Color(239, 239, 239));
        jScrollPaneCuentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneCuentas.setForeground(new java.awt.Color(52, 84, 61));
        jScrollPaneCuentas.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTableCuentas.setBackground(new java.awt.Color(240, 247, 241));
        jTableCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CUENTAS", "PESOS", "DOLARES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableCuentas.setSelectionForeground(new java.awt.Color(164, 235, 180));
        jScrollPaneCuentas.setViewportView(jTableCuentas);

        jPanelBalance.add(jScrollPaneCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 150, 528, 150));

        jLabelIngresos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelIngresos.setText("INGRESOS: $");
        jPanelBalance.add(jLabelIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 312, 122, 30));

        jLabelGastos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelGastos.setText("GASTOS:     $");
        jPanelBalance.add(jLabelGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 348, 122, 30));

        jLabelCantIngresos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCantIngresos.setText("0");
        jPanelBalance.add(jLabelCantIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 312, 260, 30));

        jLabelCantGstos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCantGstos.setText("0");
        jPanelBalance.add(jLabelCantGstos, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 348, 260, 30));

        jLabelViewImagenBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelViewImagenBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/view.png"))); // NOI18N
        jLabelViewImagenBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelViewImagenBalance.setEnabled(false);
        jPanelBalance.add(jLabelViewImagenBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 44, -1, 30));

        jLabelPrintImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/print.png"))); // NOI18N
        jLabelPrintImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPrintImagen.setEnabled(false);
        jPanelBalance.add(jLabelPrintImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 331, -1, 30));

        jLabelChartImagenBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/chart.png"))); // NOI18N
        jLabelChartImagenBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelChartImagenBalance.setEnabled(false);
        jPanelBalance.add(jLabelChartImagenBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 83, -1, 29));

        jLabelVerDineroBalance.setText("Ver dinero");
        jLabelVerDineroBalance.setEnabled(false);
        jPanelBalance.add(jLabelVerDineroBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 44, 60, 30));

        jLabelGraficosBalance.setText("Graficos");
        jLabelGraficosBalance.setEnabled(false);
        jPanelBalance.add(jLabelGraficosBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 80, 50, 32));

        jLabelImprimir.setText("Imprimir");
        jLabelImprimir.setEnabled(false);
        jPanelBalance.add(jLabelImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 331, -1, 30));

        jPanelBG.add(jPanelBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 590, 390));

        jPanelTransacciones.setBackground(new java.awt.Color(234, 242, 235));
        jPanelTransacciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitulosTransacciones.setBackground(new java.awt.Color(52, 84, 61));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("TIPO");

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("CATEGORIA");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("FECHA");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("MONEDA");

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("MONTO");

        javax.swing.GroupLayout jPanelTitulosTransaccionesLayout = new javax.swing.GroupLayout(jPanelTitulosTransacciones);
        jPanelTitulosTransacciones.setLayout(jPanelTitulosTransaccionesLayout);
        jPanelTitulosTransaccionesLayout.setHorizontalGroup(
            jPanelTitulosTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitulosTransaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitulosTransaccionesLayout.setVerticalGroup(
            jPanelTitulosTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitulosTransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelTransacciones.add(jPanelTitulosTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 510, 30));

        jLabelTransacciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTransacciones.setText("TRANSACCIONES");
        jPanelTransacciones.add(jLabelTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 19, -1, -1));

        jScrollPaneTransacciones.setBackground(new java.awt.Color(239, 239, 239));
        jScrollPaneTransacciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneTransacciones.setForeground(new java.awt.Color(52, 84, 61));
        jScrollPaneTransacciones.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTableTransacciones.setBackground(new java.awt.Color(234, 242, 235));
        jTableTransacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TIPO", "CATEGORIA", "FECHA", "MONEDA", "MONTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableTransacciones.setSelectionForeground(new java.awt.Color(164, 235, 180));
        jScrollPaneTransacciones.setViewportView(jTableTransacciones);

        jPanelTransacciones.add(jScrollPaneTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 81, 528, 154));

        jLabelSearchImagenTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/search.png"))); // NOI18N
        jLabelSearchImagenTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelTransacciones.add(jLabelSearchImagenTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 43, -1, -1));

        jLabelSortImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/sort.png"))); // NOI18N
        jLabelSortImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelTransacciones.add(jLabelSortImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 43, -1, -1));

        jLabelBuscarTransaccion.setText("Buscar transacción");
        jPanelTransacciones.add(jLabelBuscarTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 43, -1, 20));

        jLabelOrdenarPor.setText("Ordenar por");
        jPanelTransacciones.add(jLabelOrdenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 43, -1, 20));

        jPanelBG.add(jPanelTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 590, 300));

        jPanelSube.setBackground(new java.awt.Color(234, 242, 235));
        jPanelSube.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMontoSube.setText("0");
        jPanelSube.add(jLabelMontoSube, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabelSignoPesoSube.setText("$");
        jPanelSube.add(jLabelSignoPesoSube, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabelNumeroSube.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNumeroSube.setText("NUMERO SUBE");
        jPanelSube.add(jLabelNumeroSube, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabelSubeImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/subelogo.png"))); // NOI18N
        jPanelSube.add(jLabelSubeImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 293, 181));

        jLabelSube.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSube.setText("SUBE");
        jPanelSube.add(jLabelSube, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 31));

        jLabelSearchImagenSube.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSearchImagenSube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/search.png"))); // NOI18N
        jLabelSearchImagenSube.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelSube.add(jLabelSearchImagenSube, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 20, 34));

        jLabelViewImagenSube.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelViewImagenSube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/view.png"))); // NOI18N
        jLabelViewImagenSube.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelViewImagenSube.setEnabled(false);
        jPanelSube.add(jLabelViewImagenSube, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 160, 40, 34));

        jLabelBuscarSube.setText("Buscar SUBE");
        jPanelSube.add(jLabelBuscarSube, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, 34));

        jLabelVerDineroSube.setText("Ver dinero");
        jLabelVerDineroSube.setEnabled(false);
        jPanelSube.add(jLabelVerDineroSube, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, 34));

        jPanelBG.add(jPanelSube, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 560, 240));

        jPanelAhorros.setBackground(new java.awt.Color(229, 238, 230));
        jPanelAhorros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTitulosAhorros.setBackground(new java.awt.Color(52, 84, 61));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("TIPO AHORROS");
        jLabel52.setEnabled(false);

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("CANTIDAD EN USD");
        jLabel53.setEnabled(false);

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("CANTIDAD");
        jLabel54.setEnabled(false);

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("CANTIDAD EN $");
        jLabel55.setEnabled(false);

        javax.swing.GroupLayout jPanelTitulosAhorrosLayout = new javax.swing.GroupLayout(jPanelTitulosAhorros);
        jPanelTitulosAhorros.setLayout(jPanelTitulosAhorrosLayout);
        jPanelTitulosAhorrosLayout.setHorizontalGroup(
            jPanelTitulosAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitulosAhorrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitulosAhorrosLayout.setVerticalGroup(
            jPanelTitulosAhorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelAhorros.add(jPanelTitulosAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 480, 30));

        jLabelAhorros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAhorros.setText("AHORROS");
        jLabelAhorros.setEnabled(false);
        jPanelAhorros.add(jLabelAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jScrollPaneAhorros.setBackground(new java.awt.Color(239, 239, 239));
        jScrollPaneAhorros.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneAhorros.setForeground(new java.awt.Color(52, 84, 61));
        jScrollPaneAhorros.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneAhorros.setEnabled(false);

        jTableAhorros.setBackground(new java.awt.Color(234, 242, 235));
        jTableAhorros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TIPO AHORROS", "CANTIDAD", "CANTIDAD EN USD", "CANTIDAD EN PESOS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAhorros.setEnabled(false);
        jTableAhorros.setSelectionForeground(new java.awt.Color(164, 235, 180));
        jScrollPaneAhorros.setViewportView(jTableAhorros);

        jPanelAhorros.add(jScrollPaneAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 490, 154));

        jLabelCantDolaresAhorros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCantDolaresAhorros.setText("0");
        jLabelCantDolaresAhorros.setEnabled(false);
        jPanelAhorros.add(jLabelCantDolaresAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 260, -1));

        jLabelSignoDolarAhorros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSignoDolarAhorros.setText("USD");
        jLabelSignoDolarAhorros.setEnabled(false);
        jPanelAhorros.add(jLabelSignoDolarAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabelSignoPesosAhorros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSignoPesosAhorros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSignoPesosAhorros.setText("$");
        jLabelSignoPesosAhorros.setEnabled(false);
        jPanelAhorros.add(jLabelSignoPesosAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 20, -1));

        jLabelCantPesosAhorros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCantPesosAhorros.setText("0");
        jLabelCantPesosAhorros.setEnabled(false);
        jPanelAhorros.add(jLabelCantPesosAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 260, -1));

        jLabelTotalPesosEqDolares.setText("Total en Pesos y equivalente en Dolares");
        jLabelTotalPesosEqDolares.setEnabled(false);
        jPanelAhorros.add(jLabelTotalPesosEqDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabelChartImagenAhorros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/chart.png"))); // NOI18N
        jLabelChartImagenAhorros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelChartImagenAhorros.setEnabled(false);
        jPanelAhorros.add(jLabelChartImagenAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        jLabelViewImagenAhorros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/view.png"))); // NOI18N
        jLabelViewImagenAhorros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelViewImagenAhorros.setEnabled(false);
        jPanelAhorros.add(jLabelViewImagenAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabelGraficosAhorros.setText("Graficos");
        jLabelGraficosAhorros.setEnabled(false);
        jPanelAhorros.add(jLabelGraficosAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 50, 20));

        jLabelVerDineroAhorros.setText("Ver dinero");
        jLabelVerDineroAhorros.setEnabled(false);
        jPanelAhorros.add(jLabelVerDineroAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 60, 20));

        jPanelBG.add(jPanelAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 560, 290));

        jPanel7.setBackground(new java.awt.Color(240, 247, 241));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel65.setText("FUNCIONES");
        jPanel7.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabelTransactionsImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTransactionsImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/transactions.png"))); // NOI18N
        jLabelTransactionsImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTransactionsImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTransactionsImagenMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelTransactionsImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 60));

        jLabelSubeFuncionImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubeFuncionImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/sube.png"))); // NOI18N
        jLabelSubeFuncionImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSubeFuncionImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSubeFuncionImagenMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelSubeFuncionImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, 60));

        jLabelBankImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBankImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/bank.png"))); // NOI18N
        jLabelBankImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBankImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBankImagenMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelBankImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 60, 60));

        jLabelCategoriesImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCategoriesImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/categories.png"))); // NOI18N
        jLabelCategoriesImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCategoriesImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCategoriesImagenMouseClicked(evt);
            }
        });
        jPanel7.add(jLabelCategoriesImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 40, 70, 60));

        jLabelSavingsImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSavingsImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/savings.png"))); // NOI18N
        jLabelSavingsImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSavingsImagen.setEnabled(false);
        jPanel7.add(jLabelSavingsImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 60, 60));

        jLabelTransaccionesFuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTransaccionesFuncion.setText("TRANSACCIONES");
        jPanel7.add(jLabelTransaccionesFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 110, 120, -1));

        jLabelSubeFuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubeFuncion.setText("SUBE");
        jPanel7.add(jLabelSubeFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 60, -1));

        jLabelCategoriasFuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCategoriasFuncion.setText("CATEGORÍAS");
        jPanel7.add(jLabelCategoriasFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 100, -1));

        jLabelCuentasFuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCuentasFuncion.setText("CUENTAS");
        jPanel7.add(jLabelCuentasFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 60, -1));

        jLabelAhorrosFuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAhorrosFuncion.setText("AHORROS");
        jLabelAhorrosFuncion.setEnabled(false);
        jPanel7.add(jLabelAhorrosFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 60, -1));

        jLabelFondoLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/fondoLogo.png"))); // NOI18N
        jPanel7.add(jLabelFondoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 60, 60));

        jLabelFondoLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondoLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/fondoLogo.png"))); // NOI18N
        jPanel7.add(jLabelFondoLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 60));

        jLabelFondoLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondoLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/fondoLogo.png"))); // NOI18N
        jPanel7.add(jLabelFondoLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, 60));

        jLabelFondoLogo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondoLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/fondoLogo.png"))); // NOI18N
        jPanel7.add(jLabelFondoLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 60, 60));

        jLabelFondoLogo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondoLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/fondoLogo.png"))); // NOI18N
        jPanel7.add(jLabelFondoLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 60, 60));

        jPanelBG.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 560, 160));

        jMenuBar1.setBackground(new java.awt.Color(229, 238, 230));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu1.setBorder(null);
        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem1.setForeground(new java.awt.Color(229, 238, 230));
        jMenuItem1.setText("Cerrar sesión");
        jMenuItem1.setBorder(null);
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabelTransactionsImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransactionsImagenMouseClicked
        // TODO add your handling code here:
        PantallaTransacciones transaccionesPantalla = new PantallaTransacciones();
        transaccionesPantalla.setVisible(true);
        transaccionesPantalla.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabelTransactionsImagenMouseClicked

    private void jLabelSubeFuncionImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSubeFuncionImagenMouseClicked
        // TODO add your handling code here:
        PantallaSube subePantalla = new PantallaSube();
        subePantalla.setVisible(true);
        subePantalla.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabelSubeFuncionImagenMouseClicked

    private void jLabelCategoriesImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCategoriesImagenMouseClicked
        // TODO add your handling code here:
        PantallaCategorias categoriasPantalla = new PantallaCategorias();
        categoriasPantalla.setVisible(true);
        categoriasPantalla.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabelCategoriesImagenMouseClicked

    private void jLabelBankImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBankImagenMouseClicked
        // TODO add your handling code here:
        PantallaCuentas cuentasPantalla = new PantallaCuentas();
        cuentasPantalla.setVisible(true);
        cuentasPantalla.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabelBankImagenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxAnios;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabelAbril;
    private javax.swing.JLabel jLabelAgosto;
    private javax.swing.JLabel jLabelAhorros;
    private javax.swing.JLabel jLabelAhorrosFuncion;
    private javax.swing.JLabel jLabelBalance;
    private javax.swing.JLabel jLabelBankImagen;
    private javax.swing.JLabel jLabelBuscarSube;
    private javax.swing.JLabel jLabelBuscarTransaccion;
    private javax.swing.JLabel jLabelCantDolaresAhorros;
    private javax.swing.JLabel jLabelCantDolaresBalance;
    private javax.swing.JLabel jLabelCantGstos;
    private javax.swing.JLabel jLabelCantIngresos;
    private javax.swing.JLabel jLabelCantPesosAhorros;
    private javax.swing.JLabel jLabelCantPesosBalance;
    private javax.swing.JLabel jLabelCategoriasFuncion;
    private javax.swing.JLabel jLabelCategoriesImagen;
    private javax.swing.JLabel jLabelChartImagenAhorros;
    private javax.swing.JLabel jLabelChartImagenBalance;
    private javax.swing.JLabel jLabelCuentasFuncion;
    private javax.swing.JLabel jLabelDiciembre;
    private javax.swing.JLabel jLabelEnero;
    private javax.swing.JLabel jLabelFebrero;
    private javax.swing.JLabel jLabelFondoLogo;
    private javax.swing.JLabel jLabelFondoLogo1;
    private javax.swing.JLabel jLabelFondoLogo2;
    private javax.swing.JLabel jLabelFondoLogo3;
    private javax.swing.JLabel jLabelFondoLogo4;
    private javax.swing.JLabel jLabelGastos;
    private javax.swing.JLabel jLabelGraficosAhorros;
    private javax.swing.JLabel jLabelGraficosBalance;
    private javax.swing.JLabel jLabelImprimir;
    private javax.swing.JLabel jLabelIngresos;
    private javax.swing.JLabel jLabelJulio;
    private javax.swing.JLabel jLabelJunio;
    private javax.swing.JLabel jLabelMarzo;
    private javax.swing.JLabel jLabelMayo;
    private javax.swing.JLabel jLabelMontoSube;
    private javax.swing.JLabel jLabelNoviembre;
    private javax.swing.JLabel jLabelNumeroSube;
    private javax.swing.JLabel jLabelOctubre;
    private javax.swing.JLabel jLabelOrdenarPor;
    private javax.swing.JLabel jLabelPrintImagen;
    private javax.swing.JLabel jLabelSavingsImagen;
    private javax.swing.JLabel jLabelSearchImagenSube;
    private javax.swing.JLabel jLabelSearchImagenTrans;
    private javax.swing.JLabel jLabelSeptiembre;
    private javax.swing.JLabel jLabelSignoDolarAhorros;
    private javax.swing.JLabel jLabelSignoDolarBalance;
    private javax.swing.JLabel jLabelSignoPesoSube;
    private javax.swing.JLabel jLabelSignoPesosAhorros;
    private javax.swing.JLabel jLabelSignoPesosBalance;
    private javax.swing.JLabel jLabelSortImagen;
    private javax.swing.JLabel jLabelSube;
    private javax.swing.JLabel jLabelSubeFuncion;
    private javax.swing.JLabel jLabelSubeFuncionImagen;
    private javax.swing.JLabel jLabelSubeImagen;
    private javax.swing.JLabel jLabelTotalPesosDolares;
    private javax.swing.JLabel jLabelTotalPesosEqDolares;
    private javax.swing.JLabel jLabelTransacciones;
    private javax.swing.JLabel jLabelTransaccionesFuncion;
    private javax.swing.JLabel jLabelTransactionsImagen;
    private javax.swing.JLabel jLabelVerDineroAhorros;
    private javax.swing.JLabel jLabelVerDineroBalance;
    private javax.swing.JLabel jLabelVerDineroSube;
    private javax.swing.JLabel jLabelViewImagenAhorros;
    private javax.swing.JLabel jLabelViewImagenBalance;
    private javax.swing.JLabel jLabelViewImagenSube;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelAhorros;
    private javax.swing.JPanel jPanelBG;
    private javax.swing.JPanel jPanelBalance;
    private javax.swing.JPanel jPanelMeses;
    private javax.swing.JPanel jPanelSube;
    private javax.swing.JPanel jPanelTitulosAhorros;
    private javax.swing.JPanel jPanelTitulosCuentas;
    private javax.swing.JPanel jPanelTitulosTransacciones;
    private javax.swing.JPanel jPanelTransacciones;
    private javax.swing.JScrollPane jScrollPaneAhorros;
    private javax.swing.JScrollPane jScrollPaneCuentas;
    private javax.swing.JScrollPane jScrollPaneTransacciones;
    private javax.swing.JTable jTableAhorros;
    private javax.swing.JTable jTableCuentas;
    private javax.swing.JTable jTableTransacciones;
    // End of variables declaration//GEN-END:variables
}
