/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ui;

import javax.swing.ImageIcon;

/**
 *
 * @author nicle
 */
public class PantallaPresentacion extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPresentacion
     */
    public PantallaPresentacion() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/com/mycompany/images/miBilletera.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBG = new javax.swing.JPanel();
        jLabelDibujo = new javax.swing.JLabel();
        jLabelLogoMiBilletera = new javax.swing.JLabel();
        jLabelVersion = new javax.swing.JLabel();
        jLabelMiBilletera = new javax.swing.JLabel();
        jLabelGestionDeGastos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiBilletera");
        setUndecorated(true);
        setResizable(false);

        jPanelBG.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBG.setPreferredSize(new java.awt.Dimension(400, 450));
        jPanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDibujo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/imagenPresentacion.png"))); // NOI18N
        jLabelDibujo.setPreferredSize(new java.awt.Dimension(355, 355));
        jPanelBG.add(jLabelDibujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelLogoMiBilletera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/miBilleteraPresentacion.png"))); // NOI18N
        jLabelLogoMiBilletera.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanelBG.add(jLabelLogoMiBilletera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabelVersion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelVersion.setText("v1.0.0");
        jPanelBG.add(jLabelVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 100, -1));

        jLabelMiBilletera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMiBilletera.setText("MiBilletera");
        jPanelBG.add(jLabelMiBilletera, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 100, -1));

        jLabelGestionDeGastos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelGestionDeGastos.setText("Gestión de gastos");
        jPanelBG.add(jLabelGestionDeGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDibujo;
    private javax.swing.JLabel jLabelGestionDeGastos;
    private javax.swing.JLabel jLabelLogoMiBilletera;
    private javax.swing.JLabel jLabelMiBilletera;
    private javax.swing.JLabel jLabelVersion;
    private javax.swing.JPanel jPanelBG;
    // End of variables declaration//GEN-END:variables
}
