/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ui;

import com.mycompany.controller.TransactionsController;
import javax.swing.ImageIcon;

/**
 *
 * @author nicle
 */
public class SeleccionTransaccion extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionTransaccion
     */
    public SeleccionTransaccion() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/com/mycompany/images/miBilletera.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBG = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jLabelNuevaTransaccion = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelTipoValor = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelFechaValor = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelCategoriaValor = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelDescripcionValor = new javax.swing.JLabel();
        jLabelCuenta = new javax.swing.JLabel();
        jLabelCuentaValor = new javax.swing.JLabel();
        jLabelMoneda = new javax.swing.JLabel();
        jLabelMonedaValor = new javax.swing.JLabel();
        jLabelMonto = new javax.swing.JLabel();
        jLabelMontoValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi Billetera - Transaccion");
        setUndecorated(true);
        setResizable(false);

        jPanelBG.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBG.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/images/back.png"))); // NOI18N
        jLabelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBack.setPreferredSize(new java.awt.Dimension(40, 15));
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });
        jPanelBG.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 30, 20));

        jLabelNuevaTransaccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNuevaTransaccion.setText("TRANSACCIÓN SELECCIONADA");
        jPanelBG.add(jLabelNuevaTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jLabelTipo.setText("TIPO");
        jPanelBG.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 62, -1, -1));

        jLabelTipoValor.setText("XXX");
        jPanelBG.add(jLabelTipoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 84, -1, -1));

        jLabelFecha.setText("FECHA");
        jPanelBG.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 118, -1, -1));

        jLabelFechaValor.setText("dd/mm/aaaa");
        jPanelBG.add(jLabelFechaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabelCategoria.setText("CATEGORÍA");
        jPanelBG.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 174, -1, -1));

        jLabelCategoriaValor.setText("XXX");
        jPanelBG.add(jLabelCategoriaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 196, -1, -1));

        jLabelDescripcion.setText("DESCRIPCIÓN");
        jPanelBG.add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 230, -1, -1));

        jLabelDescripcionValor.setText("XXX");
        jPanelBG.add(jLabelDescripcionValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabelCuenta.setText("CUENTA");
        jPanelBG.add(jLabelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabelCuentaValor.setText("XXX");
        jPanelBG.add(jLabelCuentaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabelMoneda.setText("MONEDA");
        jPanelBG.add(jLabelMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabelMonedaValor.setText("XXX");
        jPanelBG.add(jLabelMonedaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabelMonto.setText("MONTO");
        jPanelBG.add(jLabelMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabelMontoValor.setText("XXX");
        jPanelBG.add(jLabelMontoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        // TODO add your handling code here:
        TransactionsController transactionsController = TransactionsController.getInstance();
        
        transactionsController.seleccionTransaccionCerrar();
    }//GEN-LAST:event_jLabelBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelCategoriaValor;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelCuentaValor;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDescripcionValor;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFechaValor;
    private javax.swing.JLabel jLabelMoneda;
    private javax.swing.JLabel jLabelMonedaValor;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelMontoValor;
    private javax.swing.JLabel jLabelNuevaTransaccion;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoValor;
    private javax.swing.JPanel jPanelBG;
    // End of variables declaration//GEN-END:variables
}
